name: Push Notification

on:
  # push:
  #   branches:
  #     - main
  schedule:
    - cron: '0 11 * * *' 

jobs:
  run-script:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scrapper

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.2.0'
          cache: 'npm'
          cache-dependency-path: ./scrapper/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Set environment variable
        run: echo "SERVICE_ACCOUNT_JSON=\${{ secrets.SERVICE_ACCOUNT_JSON }}" >> .env
      # - name: Set environment variable
      #   run: |
      #     BASE64_ENCODED_SECRET="${{ secrets.SERVICE_ACCOUNT_JSON }}"
      #     DECODED_SECRET=$(echo "$BASE64_ENCODED_SECRET" | base64 -d)
      #     echo "SERVICE_ACCOUNT_JSON=$DECODED_SECRET" >> .env


      - name: Run script
        run: node push_notification.js
