name: Nepse Data Auto Scrape

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 6 * * *' # runs everyday at 6 am

jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scrapper

    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Setup Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.14'
      
      - name: Install Dependencies
        run: |
          pip3 install -r requirements.txt
      
      - name: Execute Scraping Script
        run: |
          python3 ipo_scrapper.py
      - name: Commit and Push Files
        run: |
           git config --local user.email "rangeetshrestha12@gmail.com"
           git config --local user.name "Ranjit Shrestha"        
           git add .
           git commit -am "IPO scrapper ran at $(date)"
           git push origin main