name: Nepse Data Auto Scrape

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *' # runs at every 5 minutes

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Setup Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: change directory to scrapper 
        run: |
          cd scrapper
      
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Execute Scraping Script
        run: |
          python ipo_scrapper.py
      - name: Commit and Push Files
        run: |
           git config --local user.email "rangeetshrestha12@gmail.com"
           git config --local user.name "Ranjit Shrestha"        
           git add .
           git commit -am "IPO scrapper ran at $(date)"
           git push origin main